// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	data "github.com/Antvirf/metal-control-plane/internal/data"
)

type Hardwareinfo struct {
	Bmcmac string            `json:"bmcmac"`
	Info   data.HardwareInfo `json:"info"`
}
